width = 17
height = 12.0
half_width = width/2
print('width/2 =',half_width,type(half_width))
half_width2 = width/2.0
print('width/2.0 =',half_width2,type(half_width2))
height1 = height/3
print('height/3 =', height1, type(height1))
equation = 1 + 2 * 5
print('answer =',equation,type(equation))
